name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain & Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make python3-pip
          pip3 install numpy pandas
      - name: Build firmware
        run: make
      - name: Generate sample data
        run: python3 data/gen_data.py
      - name: Run unit tests
        run: make test || echo "No tests defined"
